import type { Quote, Surah } from './types';

export const QUOTES: Quote[] = [
  {
    quote: "من عمل بما علم، أورثه الله علم ما لم يعلم.",
    source: "يُنسب إلى الإمام مالك بن أنس رحمه الله"
  },
  {
    quote: "اطلبوا العلم؛ فإن عجزتم، فأحبوا أهله؛ فإن لم تحبوهم، فلا تبغضوهم.",
    source: "الإمام الشافعي رحمه الله"
  },
  {
    quote: "لو كان العلم ينفع بلا عمل، لما ذم الله أحبار أهل الكتاب.",
    source: "ابن القيم الجوزية رحمه الله"
  },
  {
    quote: "ما ندمت على سكوتي مرة، لكنني ندمت على الكلام مراراً.",
    source: "عمر بن الخطاب رضي الله عنه"
  },
  {
    quote: "إنما العلم الخشية.",
    source: "عبد الله بن مسعود رضي الله عنه"
  },
  {
    quote: "لا يزال المرء عالماً ما طلب العلم، فإذا ظن أنه قد علم، فقد جهل.",
    source: "عبد الله بن المبارك رحمه الله"
  },
  {
    quote: "رأس الحكمة مخافة الله.",
    source: "يُنسب إلى لقمان الحكيم"
  }
];

export const RECITERS: string[] = [
  "عبد الباسط عبد الصمد",
  "محمد صديق المنشاوي",
  "محمود خليل الحصري",
  "مشاري راشد العفاسي",
  "سعود الشريم",
  "عبد الرحمن السديس",
  "ماهر المعيقلي",
  "ياسر الدوسري",
  "ناصر القطامي",
  "فارس عباد"
];

export const SURAHS: Surah[] = [
    { "id": 1, "name": "الفاتحة", "total_verses": 7, "transliteration": "Al-Fatihah", "type": "Meccan" },
    { "id": 2, "name": "البقرة", "total_verses": 286, "transliteration": "Al-Baqarah", "type": "Medinan" },
    { "id": 3, "name": "آل عمران", "total_verses": 200, "transliteration": "Ali 'Imran", "type": "Medinan" },
    { "id": 4, "name": "النساء", "total_verses": 176, "transliteration": "An-Nisa", "type": "Medinan" },
    { "id": 5, "name": "المائدة", "total_verses": 120, "transliteration": "Al-Ma'idah", "type": "Medinan" },
    { "id": 6, "name": "الأنعام", "total_verses": 165, "transliteration": "Al-An'am", "type": "Meccan" },
    { "id": 7, "name": "الأعراف", "total_verses": 206, "transliteration": "Al-A'raf", "type": "Meccan" },
    { "id": 8, "name": "الأنفال", "total_verses": 75, "transliteration": "Al-Anfal", "type": "Medinan" },
    { "id": 9, "name": "التوبة", "total_verses": 129, "transliteration": "At-Tawbah", "type": "Medinan" },
    { "id": 10, "name": "يونس", "total_verses": 109, "transliteration": "Yunus", "type": "Meccan" },
    { "id": 11, "name": "هود", "total_verses": 123, "transliteration": "Hud", "type": "Meccan" },
    { "id": 12, "name": "يوسف", "total_verses": 111, "transliteration": "Yusuf", "type": "Meccan" },
    { "id": 13, "name": "الرعد", "total_verses": 43, "transliteration": "Ar-Ra'd", "type": "Meccan" },
    { "id": 14, "name": "ابراهيم", "total_verses": 52, "transliteration": "Ibrahim", "type": "Meccan" },
    { "id": 15, "name": "الحجر", "total_verses": 99, "transliteration": "Al-Hijr", "type": "Meccan" },
    { "id": 16, "name": "النحل", "total_verses": 128, "transliteration": "An-Nahl", "type": "Meccan" },
    { "id": 17, "name": "الإسراء", "total_verses": 111, "transliteration": "Al-Isra", "type": "Meccan" },
    { "id": 18, "name": "الكهف", "total_verses": 110, "transliteration": "Al-Kahf", "type": "Meccan" },
    { "id": 19, "name": "مريم", "total_verses": 98, "transliteration": "Maryam", "type": "Meccan" },
    { "id": 20, "name": "طه", "total_verses": 135, "transliteration": "Taha", "type": "Meccan" },
    { "id": 21, "name": "الأنبياء", "total_verses": 112, "transliteration": "Al-Anbya", "type": "Meccan" },
    { "id": 22, "name": "الحج", "total_verses": 78, "transliteration": "Al-Hajj", "type": "Medinan" },
    { "id": 23, "name": "المؤمنون", "total_verses": 118, "transliteration": "Al-Mu'minun", "type": "Meccan" },
    { "id": 24, "name": "النور", "total_verses": 64, "transliteration": "An-Nur", "type": "Medinan" },
    { "id": 25, "name": "الفرقان", "total_verses": 77, "transliteration": "Al-Furqan", "type": "Meccan" },
    { "id": 26, "name": "الشعراء", "total_verses": 227, "transliteration": "Ash-Shu'ara", "type": "Meccan" },
    { "id": 27, "name": "النمل", "total_verses": 93, "transliteration": "An-Naml", "type": "Meccan" },
    { "id": 28, "name": "القصص", "total_verses": 88, "transliteration": "Al-Qasas", "type": "Meccan" },
    { "id": 29, "name": "العنكبوت", "total_verses": 69, "transliteration": "Al-'Ankabut", "type": "Meccan" },
    { "id": 30, "name": "الروم", "total_verses": 60, "transliteration": "Ar-Rum", "type": "Meccan" },
    { "id": 31, "name": "لقمان", "total_verses": 34, "transliteration": "Luqman", "type": "Meccan" },
    { "id": 32, "name": "السجدة", "total_verses": 30, "transliteration": "As-Sajdah", "type": "Meccan" },
    { "id": 33, "name": "الأحزاب", "total_verses": 73, "transliteration": "Al-Ahzab", "type": "Medinan" },
    { "id": 34, "name": "سبأ", "total_verses": 54, "transliteration": "Saba", "type": "Meccan" },
    { "id": 35, "name": "فاطر", "total_verses": 45, "transliteration": "Fatir", "type": "Meccan" },
    { "id": 36, "name": "يس", "total_verses": 83, "transliteration": "Ya-Sin", "type": "Meccan" },
    { "id": 37, "name": "الصافات", "total_verses": 182, "transliteration": "As-Saffat", "type": "Meccan" },
    { "id": 38, "name": "ص", "total_verses": 88, "transliteration": "Sad", "type": "Meccan" },
    { "id": 39, "name": "الزمر", "total_verses": 75, "transliteration": "Az-Zumar", "type": "Meccan" },
    { "id": 40, "name": "غافر", "total_verses": 85, "transliteration": "Ghafir", "type": "Meccan" },
    { "id": 41, "name": "فصلت", "total_verses": 54, "transliteration": "Fussilat", "type": "Meccan" },
    { "id": 42, "name": "الشورى", "total_verses": 53, "transliteration": "Ash-Shuraa", "type": "Meccan" },
    { "id": 43, "name": "الزخرف", "total_verses": 89, "transliteration": "Az-Zukhruf", "type": "Meccan" },
    { "id": 44, "name": "الدخان", "total_verses": 59, "transliteration": "Ad-Dukhan", "type": "Meccan" },
    { "id": 45, "name": "الجاثية", "total_verses": 37, "transliteration": "Al-Jathiyah", "type": "Meccan" },
    { "id": 46, "name": "الأحقاف", "total_verses": 35, "transliteration": "Al-Ahqaf", "type": "Meccan" },
    { "id": 47, "name": "محمد", "total_verses": 38, "transliteration": "Muhammad", "type": "Medinan" },
    { "id": 48, "name": "الفتح", "total_verses": 29, "transliteration": "Al-Fath", "type": "Medinan" },
    { "id": 49, "name": "الحجرات", "total_verses": 18, "transliteration": "Al-Hujurat", "type": "Medinan" },
    { "id": 50, "name": "ق", "total_verses": 45, "transliteration": "Qaf", "type": "Meccan" },
    { "id": 51, "name": "الذاريات", "total_verses": 60, "transliteration": "Adh-Dhariyat", "type": "Meccan" },
    { "id": 52, "name": "الطور", "total_verses": 49, "transliteration": "At-Tur", "type": "Meccan" },
    { "id": 53, "name": "النجم", "total_verses": 62, "transliteration": "An-Najm", "type": "Meccan" },
    { "id": 54, "name": "القمر", "total_verses": 55, "transliteration": "Al-Qamar", "type": "Meccan" },
    { "id": 55, "name": "الرحمن", "total_verses": 78, "transliteration": "Ar-Rahman", "type": "Medinan" },
    { "id": 56, "name": "الواقعة", "total_verses": 96, "transliteration": "Al-Waqi'ah", "type": "Meccan" },
    { "id": 57, "name": "الحديد", "total_verses": 29, "transliteration": "Al-Hadid", "type": "Medinan" },
    { "id": 58, "name": "المجادلة", "total_verses": 22, "transliteration": "Al-Mujadila", "type": "Medinan" },
    { "id": 59, "name": "الحشر", "total_verses": 24, "transliteration": "Al-Hashr", "type": "Medinan" },
    { "id": 60, "name": "الممتحنة", "total_verses": 13, "transliteration": "Al-Mumtahanah", "type": "Medinan" },
    { "id": 61, "name": "الصف", "total_verses": 14, "transliteration": "As-Saf", "type": "Medinan" },
    { "id": 62, "name": "الجمعة", "total_verses": 11, "transliteration": "Al-Jumu'ah", "type": "Medinan" },
    { "id": 63, "name": "المنافقون", "total_verses": 11, "transliteration": "Al-Munafiqun", "type": "Medinan" },
    { "id": 64, "name": "التغابن", "total_verses": 18, "transliteration": "At-Taghabun", "type": "Medinan" },
    { "id": 65, "name": "الطلاق", "total_verses": 12, "transliteration": "At-Talaq", "type": "Medinan" },
    { "id": 66, "name": "التحريم", "total_verses": 12, "transliteration": "At-Tahrim", "type": "Medinan" },
    { "id": 67, "name": "الملك", "total_verses": 30, "transliteration": "Al-Mulk", "type": "Meccan" },
    { "id": 68, "name": "القلم", "total_verses": 52, "transliteration": "Al-Qalam", "type": "Meccan" },
    { "id": 69, "name": "الحاقة", "total_verses": 52, "transliteration": "Al-Haqqah", "type": "Meccan" },
    { "id": 70, "name": "المعارج", "total_verses": 44, "transliteration": "Al-Ma'arij", "type": "Meccan" },
    { "id": 71, "name": "نوح", "total_verses": 28, "transliteration": "Nuh", "type": "Meccan" },
    { "id": 72, "name": "الجن", "total_verses": 28, "transliteration": "Al-Jinn", "type": "Meccan" },
    { "id": 73, "name": "المزمل", "total_verses": 20, "transliteration": "Al-Muzzammil", "type": "Meccan" },
    { "id": 74, "name": "المدثر", "total_verses": 56, "transliteration": "Al-Muddaththir", "type": "Meccan" },
    { "id": 75, "name": "القيامة", "total_verses": 40, "transliteration": "Al-Qiyamah", "type": "Meccan" },
    { "id": 76, "name": "الانسان", "total_verses": 31, "transliteration": "Al-Insan", "type": "Medinan" },
    { "id": 77, "name": "المرسلات", "total_verses": 50, "transliteration": "Al-Mursalat", "type": "Meccan" },
    { "id": 78, "name": "النبأ", "total_verses": 40, "transliteration": "An-Naba", "type": "Meccan" },
    { "id": 79, "name": "النازعات", "total_verses": 46, "transliteration": "An-Nazi'at", "type": "Meccan" },
    { "id": 80, "name": "عبس", "total_verses": 42, "transliteration": "'Abasa", "type": "Meccan" },
    { "id": 81, "name": "التكوير", "total_verses": 29, "transliteration": "At-Takwir", "type": "Meccan" },
    { "id": 82, "name": "الإنفطار", "total_verses": 19, "transliteration": "Al-Infitar", "type": "Meccan" },
    { "id": 83, "name": "المطففين", "total_verses": 36, "transliteration": "Al-Mutaffifin", "type": "Meccan" },
    { "id": 84, "name": "الإنشقاق", "total_verses": 25, "transliteration": "Al-Inshiqaq", "type": "Meccan" },
    { "id": 85, "name": "البروج", "total_verses": 22, "transliteration": "Al-Buruj", "type": "Meccan" },
    { "id": 86, "name": "الطارق", "total_verses": 17, "transliteration": "At-Tariq", "type": "Meccan" },
    { "id": 87, "name": "الأعلى", "total_verses": 19, "transliteration": "Al-A'la", "type": "Meccan" },
    { "id": 88, "name": "الغاشية", "total_verses": 26, "transliteration": "Al-Ghashiyah", "type": "Meccan" },
    { "id": 89, "name": "الفجر", "total_verses": 30, "transliteration": "Al-Fajr", "type": "Meccan" },
    { "id": 90, "name": "البلد", "total_verses": 20, "transliteration": "Al-Balad", "type": "Meccan" },
    { "id": 91, "name": "الشمس", "total_verses": 15, "transliteration": "Ash-Shams", "type": "Meccan" },
    { "id": 92, "name": "الليل", "total_verses": 21, "transliteration": "Al-Layl", "type": "Meccan" },
    { "id": 93, "name": "الضحى", "total_verses": 11, "transliteration": "Ad-Duhaa", "type": "Meccan" },
    { "id": 94, "name": "الشرح", "total_verses": 8, "transliteration": "Ash-Sharh", "type": "Meccan" },
    { "id": 95, "name": "التين", "total_verses": 8, "transliteration": "At-Tin", "type": "Meccan" },
    { "id": 96, "name": "العلق", "total_verses": 19, "transliteration": "Al-'Alaq", "type": "Meccan" },
    { "id": 97, "name": "القدر", "total_verses": 5, "transliteration": "Al-Qadr", "type": "Meccan" },
    { "id": 98, "name": "البينة", "total_verses": 8, "transliteration": "Al-Bayyinah", "type": "Medinan" },
    { "id": 99, "name": "الزلزلة", "total_verses": 8, "transliteration": "Az-Zalzalah", "type": "Medinan" },
    { "id": 100, "name": "العاديات", "total_verses": 11, "transliteration": "Al-'Adiyat", "type": "Meccan" },
    { "id": 101, "name": "القارعة", "total_verses": 11, "transliteration": "Al-Qari'ah", "type": "Meccan" },
    { "id": 102, "name": "التكاثر", "total_verses": 8, "transliteration": "At-Takathur", "type": "Meccan" },
    { "id": 103, "name": "العصر", "total_verses": 3, "transliteration": "Al-'Asr", "type": "Meccan" },
    { "id": 104, "name": "الهمزة", "total_verses": 9, "transliteration": "Al-Humazah", "type": "Meccan" },
    { "id": 105, "name": "الفيل", "total_verses": 5, "transliteration": "Al-Fil", "type": "Meccan" },
    { "id": 106, "name": "قريش", "total_verses": 4, "transliteration": "Quraysh", "type": "Meccan" },
    { "id": 107, "name": "الماعون", "total_verses": 7, "transliteration": "Al-Ma'un", "type": "Meccan" },
    { "id": 108, "name": "الكوثر", "total_verses": 3, "transliteration": "Al-Kawthar", "type": "Meccan" },
    { "id": 109, "name": "الكافرون", "total_verses": 6, "transliteration": "Al-Kafirun", "type": "Meccan" },
    { "id": 110, "name": "النصر", "total_verses": 3, "transliteration": "An-Nasr", "type": "Medinan" },
    { "id": 111, "name": "المسد", "total_verses": 5, "transliteration": "Al-Masad", "type": "Meccan" },
    { "id": 112, "name": "الإخلاص", "total_verses": 4, "transliteration": "Al-Ikhlas", "type": "Meccan" },
    { "id": 113, "name": "الفلق", "total_verses": 5, "transliteration": "Al-Falaq", "type": "Meccan" },
    { "id": 114, "name": "الناس", "total_verses": 6, "transliteration": "An-Nas", "type": "Meccan" }
];